import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from a2wsgi import ASGIMiddleware

from routers import omr

app = FastAPI(title="Gabarito Fácil API Exclusiva de IA")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(omr.router, prefix="/api")

# Serve the Vite/React frontend
# The 'dist' folder is generated by running `npm run build` in the root frontend directory.
# Since main.py runs inside the 'backend' folder, the 'dist' folder is physically located at '../dist'
frontend_dist = os.path.join(os.path.dirname(__dirname), "dist")

if os.path.isdir(frontend_dist):
    # Serve all static files from root
    app.mount("/assets", StaticFiles(directory=os.path.join(frontend_dist, "assets")), name="assets")
    app.mount("/icons", StaticFiles(directory=os.path.join(frontend_dist, "icons")), name="icons")

    @app.get("/{full_path:path}")
    async def serve_react_app(full_path: str):
        # Allow serving root index.html, robots.txt, sw.js, etc.
        file_path = os.path.join(frontend_dist, full_path)
        if os.path.isfile(file_path):
            return FileResponse(file_path)
        # Fallback to index.html for Single Page Applications (Routing)
        return FileResponse(os.path.join(frontend_dist, "index.html"))
else:
    @app.get("/")
    def read_root():
        return {"status": "ok", "message": "API rodando! Para ver o site, mude para a pasta frontend e use 'npm run build'."}

# PythonAnywhere WSGI Application entry point
# PythonAnywhere uses WSGI instances, but FastAPI is an ASGI app.
# a2wsgi acts as a translator allowing PythonAnywhere to run FastAPI seamlessly.
application = ASGIMiddleware(app)

